CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

INSERT INTO `ROLE` (`ID`, `NAME`) VALUES
	(1, 'ROLE_ADMIN'),
	(2, 'ROLE_TEACHER');



	CREATE TABLE IF NOT EXISTS `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE` bit(1) DEFAULT NULL,
  `LOGIN` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `ROLE` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_LOGIN` (`LOGIN`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

ALTER TABLE `USER` ADD CONSTRAINT `FK_USER_ROLE` FOREIGN KEY (ROLE) REFERENCES ROLE(ID);
