CREATE TABLE IF NOT EXISTS `GROUPS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `ACTIVE` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_GROUP_NAME` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

INSERT INTO `GROUPS` (`ID`, `NAME`, `ACTIVE`) VALUES
	(1, 'KE-12',1),
	(2, 'KI-12',1);



CREATE TABLE IF NOT EXISTS `GROUP_SUBJECT` (
  `GROUP_ID` int(11) NOT NULL,
  `SUBJECT_ID` int(11) NOT NULL,
  PRIMARY KEY (`GROUP_ID`,`SUBJECT_ID`),
  CONSTRAINT `FK_GROUP_SUBJECT_GROUP` FOREIGN KEY (`GROUP_ID`) REFERENCES `GROUPS` (`ID`),
  CONSTRAINT `FK_GROUP_SUBJECT_SUBJECT` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `SUBJECT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
